apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-rest-helloworld.fullname" . }}-config
  labels:
      app: {{ include "spring-rest-helloworld.fullname" . }}-config
data:
  {{ .Values.volumeMounts.configSubPath }}: |
    server:
      servlet:
        contextPath: /spring-k8s
    target:
      application: spring-k8s
      description: Testing kubernetes deployment,service,configMap,secret,ingress.