apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-rest-helloworld.fullname" . }}-config
  labels:
    app: {{ include "spring-rest-helloworld.fullname" . }}

data:

  application-config-override.yaml: |
    server:
      servlet:
        contextPath: /myapp
    target:
      application: spring-rest-helloworld
      description: Testing kubernetes deployment,service,configMap,secret,ingress.